#!/bin/bash
# Store file list provided in parameters
# to be pasted later

echo starting copy $@

P=$HOME/.paths_to_link.txt

[ -e $P ] && rm "$P"

IFS=$'\n'
for p in "$@"; do
	echo "${PWD}/$p" >> $P
done
