#!/bin/bash

function nameAtDest() {
	folder="$1"
	filename="$2"
	destination="${folder}/${filename}"

	basename="${filename%%.*}"
	extension="${filename##*.}"

	i=0
	while [ -f $destination ]
	do
		destination="$1/${basename}_${i}.${extension}"
		i=$(( i + 1 ))
	done
	echo "$destination"
}

LOG=$HOME/test.log

# Get file list
IFS=$'\r\n'
paths=$( wl-paste )
echo paths: $paths | tee $LOG

case "$1" in
	--hardlink) flags="";;
	--symlink) flags="-s";;
	*) echo "Unrecognised first argument"; exit 1;
esac


dest="$PWD"

for p in $paths; do
	filename="$(basename "$p")"
	destination=$(nameAtDest "$dest" "$filename")
	echo "Creating $destination" | tee $LOG
	ln $flags "$p" "$destination" | tee $LOG
done
