#!/bin/bash

LOG=$HOME/test.log

echo $(date) pwd=$(pwd) "$@" | tee $LOG
IFS=$'\n'
paths=$( cat $HOME/.paths_to_link.txt )
echo paths: $paths | tee $LOG

dest="$PWD"

for p in $paths; do
	echo "$p"
	ln -s "$p" "$dest" | tee $LOG
done 
